[Version]
Signature        = "$CHICAGO$"
DEVTYPE_INI_FILE = 1
INI_ORDER        = 200

[UIUSetupCfg]
COMMAND_LINE=-SM=SMARTAUDIO.EXE,1801

[Manufacturer]
Conexant = Conexant

[Conexant]
Conexant = HdAudModel, HDAUDIO\FUNC_01&VEN_14F1
;;Conexant = HdPostModel, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA506F
;;Conexant = HdPostModel, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA5070

[HdPostModel]
CabFile      = SAIICabFile
InstallApp   = SAIIPostInstallApp

[HdPostModel.NTamd64]
CabFile      = SAIICabFile
InstallApp   = SAIIPostInstallApp

[HdAudModel]
CabFile      = SAIICabFile
InstallApp   = SAIIInstallApp

[HdAudModel.NTamd64]
CabFile      = SAIICabFile
InstallApp   = SAIIInstallApp

[SAIICabFile]
CabFile      = saii.cab,,1

[SAIIPostInstallApp]
InstallApp = "SAII\Setup.exe",,0x00040001,"Conexant SmartAudio",,,600

[SAIIInstallApp]
InstallApp = "SAII\Setup.exe",,0x201,"Conexant SmartAudio",,,1
