[Version]
Signature = "$CHICAGO$"
DEVTYPE_INI_FILE = 1
INI_ORDER        = 100

[FLAGS]
CTY_PARMS = 0
Reboot = 1

[Manufacturer]
Conexant = Conexant, NTamd64

[Conexant.NTx86.6.1]
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA504C ; JPN
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2238 ; JPN 

[Conexant.NTx86.6.2]

[Conexant.NTx86.6.3]
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA504C ; JPN
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2238 ; JPN 

[Conexant.NTx86.6.4]
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA504C ; JPN
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2238 ; JPN 
Conexant = HdAudModel2, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2237

[Conexant.NTamd64.6.1]
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA504C ; JPN
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2238 ; JPN 

[Conexant.NTamd64.6.2]

[Conexant.NTamd64.6.3]
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA504C ; JPN
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2238 ; JPN 

[Conexant.NTamd64.6.4]
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2238 ; JPN
Conexant = HdAudModel1, HDAUDIO\FUNC_01&VEN_14F1&DEV_2008&SUBSYS_17AA224E ; JPN
Conexant = HdAudModel2, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA2237
Conexant = HdAudModel3, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA505B
Conexant = HdAudModel3, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA505C
Conexant = HdAudModel4, HDAUDIO\FUNC_01&VEN_14F1&DEV_2008&SUBSYS_17AA224F ; JPN ;;yoda
Conexant = HdAudModel5, HDAUDIO\FUNC_01&VEN_14F1&DEV_2008&SUBSYS_17AA5061 ; Storm2
Conexant = HdAudModel6, HDAUDIO\FUNC_01&VEN_14F1&DEV_2008&SUBSYS_17AA5066 ; Merlyn2
Conexant = HdAudModel7, HDAUDIO\FUNC_01&VEN_14F1&DEV_2008&SUBSYS_17AA224E ; JPN ;;Raven2
Conexant = HdAudModel8, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA504C ; JPN Carling
Conexant = HdAudModel9, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA506F ; EX85 2017
Conexant = HdAudModel9, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA5070 ; EX85 2017
Conexant = HdAudModel10, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA5068 ; EX85 2017
Conexant = HdAudModel11, HDAUDIO\FUNC_01&VEN_14F1&DEV_5111&SUBSYS_17AA5069 ; EX85 2017
Conexant = HdAudModel12, HDAUDIO\FUNC_01&VEN_14F1&DEV_2008&SUBSYS_17AA506D ; Storm3

[HdAudModel1]
AddReg = Cortana.AddReg, SpkName.AddReg

[HdAudModel2]
AddReg = Cortana.AddReg, ResumeDelay.AddReg

[HdAudModel3]
AddReg = MicArray.AddReg

[HdAudModel4]
AddReg = Cortana.AddReg, SpkName.AddReg, ArrayYoda.AddReg

[HdAudModel5]
AddReg = Cortana.AddReg, ArrayStorm2.AddReg, ExtMicSVH.AddReg, Storm.AddReg

[HdAudModel6]
AddReg = Cortana.AddReg, ExtMicGain.AddReg, ExtMicSVH.AddReg

[HdAudModel7]
AddReg = Cortana.AddReg, RenderMute.AddReg

[HdAudModel8]
AddReg = Cortana.AddReg, SpkName.AddReg, MicVol.AddReg

[HdAudModel9]
AddReg = Cortana.AddReg, HP.AddReg, NoAPOMute.AddReg

[HdAudModel10]
AddReg = Cortana1.AddReg, SWITCH.AddReg, GSMark.AddReg

[HdAudModel11]
AddReg = Cortana.AddReg, SWITCH.AddReg, GSMark.AddReg

[HdAudModel12]
AddReg = Cortana2.AddReg, Storm.AddReg, Storm3.AddReg

[Cortana.AddReg]
HKLM,Software\Microsoft\Speech_OneCore\AudioInput\MicWiz,DefaultDefaultMicGain, 0x00010001, 0x00002710 

[Cortana1.AddReg]
HKLM,Software\Microsoft\Speech_OneCore\AudioInput\MicWiz,DefaultDefaultMicGain, 0x00010001, 0x00001F40 

[Cortana2.AddReg]
HKLM,Software\Microsoft\Speech_OneCore\AudioInput\MicWiz,DefaultDefaultMicGain, 0x00010001, 0x0000251C

[SpkName.AddReg]
HKR,"Settings\EPattributes\EpSettings",SpeakerWithHPName,1,01 

[MicArray.AddReg]
HKR,Settings\MicArrayInfo,MicCoordXY01,1,00,00,3C,00  ;;Low word: Coordinate X, High word: Coordinate Y

[MicVol.AddReg]
HKR,GlobalSettings\AnalogDigitalCapture2\Node000,Chan000, 0x00010001, 0xfff85020
HKR,GlobalSettings\AnalogDigitalCapture2\Node000,Chan001, 0x00010001, 0xfff85020

[ArrayYoda.AddReg]
HKR,Settings\MicArrayInfo,MicCoordXY01,1,00,00,32,00  ;;Low word: Coordinate X, High word: Coordinate Y

[ArrayStorm2.AddReg]
HKR,Settings\MicArrayInfo,MicCoordXY01,1,00,00,32,00  ;;Low word: Coordinate X, High word: Coordinate Y

[RenderMute.AddReg]
;;HKR,Settings\OEM,RenderMuteTime,1,0f,00,00,00

[ExtMicGain.AddReg]
HKR,Settings\OEM\MicInRange,ExtHsMicGainAdded,1,00,00,18,00
HKR,Settings\OEM,ResumeDelayPeriodInMs,1,F4,01,00,00

[ExtMicSVH.AddReg]
HKR,Settings\OEM,SoftVolumeHw,1,01,00,00,00

[ResumeDelay.AddReg]
HKR,Settings\OEM,ResumeDelayPeriodInMs,1,D0,07,00,00

[HP.AddReg]
HKR,Settings\OEM,InvertPalmPortBSense,1,00,00,00,00 ;;  Port B sense opposite

[SWITCH.AddReg]
HKR,Settings\EPattributes\EPSettings\HeadsetCtrlEnable,EnableFastSwitch,1,00,00,00,00;
HKR,Settings\OEM,ForceJackUseDetectionTime,1,00,00,00,00

[GSMark.AddReg] 
;;HKLM,System\CurrentControlSet\Control\Conexant\OverrideVerbs,1, 0x00010001, 0x00171F01 
;;HKR,Settings\OEM,AppsUpdates,1,E8,00,0C,00 
;;HKR,Settings\OEM,AmpHeadPhoneProtection ,1,01,00,00,00 

[Storm.AddReg] 
HKR,Settings\OEM,MuteSpkWhenSuspendM2,1,00,00,00,00

[Storm3.AddReg] 
HKR,Settings\OEM\FlexSettings,Flex_MasterPlaybackVolume,0x00000001,5F,00,00,00
HKR,Settings\OEM,EnableInlineControl,1,01,00,00,00
HKR,Settings\OEM,MuteSpkWhenSuspend,1,00,00,00,00

[NoAPOMute.AddReg] 
HKR,Settings\OEM,ApoEnableMuteMicWhenRecording,1,00,00,00,00
