;******************************************************
;*  For Power Manager (Vista)                         *
;*            PWMPDFV1.ini                            *
;******************************************************
;******************************************************
;*  Predefined power scheme data                      *
;******************************************************
;Schemes=Total of predefined power schemes
;
; Control section
;
[CONTROL]
Schemes=8
CodePage=1251

;*****************************************
;*  predefined power scheme data         *
;*****************************************
;SchemeName=Power scheme name
;Description=Power scheme description

;------------------------------------------
;
; Maximum Performance
;
[PWRSCHM0]
SchemeName=Максимальна продуктивність
Description=
;
; Maximum Battery Life
;
[PWRSCHM1]
SchemeName=Максимальний час роботи від акумулятора
Description=
;
; Timers off(Presentation)
;
[PWRSCHM2]
SchemeName=Таймери вимкнуто (Презентація)
Description=
;
; Power Source Optimized
;
[PWRSCHM3]
SchemeName=Оптимізоване джерело живлення
Description=
;
; Low Fan Sound Level
;
[PWRSCHM4]
SchemeName=Низький рівень шуму вентиляторів
Description=
;
; Low System Temperature
;
[PWRSCHM5]
SchemeName=Низька температура системи
Description=
;
; Video Playback
;
[PWRSCHM6]
SchemeName=Відтворення відео
Description=
;
; Airplane in-seat
;
[PWRSCHM7]
SchemeName=У літаку
Description=