;******************************************************
;*  For Power Manager (Vista)                         *
;*            PWMPDFV1.ini                            *
;******************************************************
;******************************************************
;*  Predefined power scheme data                      *
;******************************************************
;Schemes=Total of predefined power schemes
;
; Control section
;
[CONTROL]
Schemes=8
CodePage=950

;*****************************************
;*  predefined power scheme data         *
;*****************************************
;SchemeName=Power scheme name
;Description=Power scheme description

;------------------------------------------
;
; Maximum Performance
;
[PWRSCHM0]
SchemeName=程蔼
Description=
;
; Maximum Battery Life
;
[PWRSCHM1]
SchemeName=程筿关㏑
Description=
;
; Timers off(Presentation)
;
[PWRSCHM2]
SchemeName=璸竟闽超甶ボ糷
Description=
;
; Power Source Optimized
;
[PWRSCHM3]
SchemeName=程ㄎて筿方
Description=
;
; Low Fan Sound Level
;
[PWRSCHM4]
SchemeName=秖单
Description=
;
; Low System Temperature
;
[PWRSCHM5]
SchemeName=╰参放
Description=
;
; Video Playback
;
[PWRSCHM6]
SchemeName=跌癟冀
Description=
;
; Airplane in-seat
;
[PWRSCHM7]
SchemeName=诀康筿方家Α
Description=
