;******************************************************
;*  For Power Manager (Vista)                         *
;*            PWMPDFV1.ini                            *
;******************************************************
;******************************************************
;*  Predefined power scheme data                      *
;******************************************************
;Schemes=Total of predefined power schemes
;
; Control section
;
[CONTROL]
Schemes=8
CodePage=1252

;*****************************************
;*  predefined power scheme data         *
;*****************************************
;SchemeName=Power scheme name
;Description=Power scheme description

;------------------------------------------
;
; Maximum Performance
;
[PWRSCHM0]
SchemeName=Desempenho Máximo
Description=
;
; Maximum Battery Life
;
[PWRSCHM1]
SchemeName=Vida Útil Máxima da Bateria
Description=
;
; Timers off(Presentation)
;
[PWRSCHM2]
SchemeName=Temporizadores desligados
Description=
;
; Power Source Optimized
;
[PWRSCHM3]
SchemeName=Fonte de Alimentação Otimizada
Description=
;
; Low Fan Sound Level
;
[PWRSCHM4]
SchemeName=Nível de Som do Ventilador Baixo
Description=
;
; Low System Temperature
;
[PWRSCHM5]
SchemeName=Temperatura do Sistema Baixa
Description=
;
; Video Playback
;
[PWRSCHM6]
SchemeName=Reprodução de Vídeo
Description=
;
; Airplane in-seat
;
[PWRSCHM7]
SchemeName=Modo de Energia de Avião
Description=