;******************************************************
;*  For Power Manager (Vista)                         *
;*            PWMPDFV1.ini                            *
;******************************************************
;******************************************************
;*  Predefined power scheme data                      *
;******************************************************
;Schemes=Total of predefined power schemes
;
; Control section
;
[CONTROL]
Schemes=8
CodePage=1256

;*****************************************
;*  predefined power scheme data         *
;*****************************************
;SchemeName=Power scheme name
;Description=Power scheme description

;------------------------------------------
;
; Maximum Performance
;
[PWRSCHM0]
SchemeName=«·Õœ «·√ﬁ’Ï ··√œ«¡
Description=
;
; Maximum Battery Life
;
[PWRSCHM1]
SchemeName=«·Õœ «·√ﬁ’Ï ·⁄„— «·»ÿ«—Ì…
Description=
;
; Timers off(Presentation)
;
[PWRSCHM2]
SchemeName=≈Ìﬁ«›  ‘€Ì· «·„ƒﬁ «  ( ﬁœÌ„Ì)
Description=
;
; Power Source Optimized
;
[PWRSCHM3]
SchemeName= Õ”Ì‰ „’œ— «·ÿ«ﬁ…
Description=
;
; Low Fan Sound Level
;
[PWRSCHM4]
SchemeName=„” ÊÏ ’Ê  «·„—ÊÕ… «·„‰Œ›÷
Description=
;
; Low System Temperature
;
[PWRSCHM5]
SchemeName=œ—Ã… Õ—«—… «·‰Ÿ«„ «·„‰Œ›÷…
Description=
;
; Video Playback
;
[PWRSCHM6]
SchemeName= ‘€Ì· «·›ÌœÌÊ
Description=
;
; Airplane in-seat
;
[PWRSCHM7]
SchemeName=«·ÿ«∆—…
Description=