;******************************************************
;*  For Power Manager (Vista)                         *
;*            PWMPDFV1.ini                            *
;******************************************************
;******************************************************
;*  Predefined power scheme data                      *
;******************************************************
;Schemes=Total of predefined power schemes
;
; Control section
;
[CONTROL]
Schemes=8
CodePage=932

;*****************************************
;*  predefined power scheme data         *
;*****************************************
;SchemeName=Power scheme name
;Description=Power scheme description

;------------------------------------------
;
; Maximum Performance
;
[PWRSCHM0]
SchemeName=ﾏｯｸｽ･ﾊﾟﾌｫｰﾏﾝｽ
Description=
;
; Maximum Battery Life
;
[PWRSCHM1]
SchemeName=ﾏｯｸｽ･ﾊﾞｯﾃﾘｰ･ﾗｲﾌ
Description=
;
; Timers off(Presentation)
;
[PWRSCHM2]
SchemeName=ﾀｲﾏｰ禁止 (ﾌﾟﾚｾﾞﾝﾃｰｼｮﾝ)
Description=
;
; Power Source Optimized
;
[PWRSCHM3]
SchemeName=ﾊﾟﾜｰ源最適化
Description=
;
; Low Fan Sound Level
;
[PWRSCHM4]
SchemeName=ｻｲﾚﾝﾄ
Description=
;
; Low System Temperature
;
[PWRSCHM5]
SchemeName=低温
Description=
;
; Video Playback
;
[PWRSCHM6]
SchemeName=ﾋﾞﾃﾞｵの再生
Description=
;
; Airplane in-seat
;
[PWRSCHM7]
SchemeName=飛行機搭乗モード
Description=
