;******************************************************
;*  For Power Manager (Vista)                         *
;*            PWMPDFV1.ini                            *
;******************************************************
;******************************************************
;*  Predefined power scheme data                      *
;******************************************************
;Schemes=Total of predefined power schemes
;
; Control section
;
[CONTROL]
Schemes=8
CodePage=1255

;*****************************************
;*  predefined power scheme data         *
;*****************************************
;SchemeName=Power scheme name
;Description=Power scheme description

;------------------------------------------
;
; Maximum Performance
;
[PWRSCHM0]
SchemeName=ביצועים מרביים
Description=
;
; Maximum Battery Life
;
[PWRSCHM1]
SchemeName=חיי סוללה מרביים
Description=
;
; Timers off(Presentation)
;
[PWRSCHM2]
SchemeName=קוצבי זמן כבויים (מצגת)
Description=
;
; Power Source Optimized
;
[PWRSCHM3]
SchemeName=מיטוב מקור מתח
Description=
;
; Low Fan Sound Level
;
[PWRSCHM4]
SchemeName=צליל מאוורר חלש
Description=
;
; Low System Temperature
;
[PWRSCHM5]
SchemeName=טמפרטורת מערכת נמוכה
Description=
;
; Video Playback
;
[PWRSCHM6]
SchemeName=הפעלת וידאו
Description=
;
; Airplane in-seat
;
[PWRSCHM7]
SchemeName=טיסה
Description=